### PR TITLE
Noetic support For Gentoo

### PR DESCRIPTION
**Pull request by allenh1**
Signed-off-by: Hunter L. Allen <hunter.allen@ghostrobotics.io>

### CODE REVIEW

**Review by tfoote — COMMENTED** [review]
Looks reasonable. The chunking is because there's too many to generate at once?

**Comment by allenh1** [comment]
Yeah, that's it exactly. It needs more testing, but seemed to work on my pc when I gave it a go.

Got a bit lazy about pushing updates, and they've stacked up pretty high at this point.

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
How about mentioning in the comment message and PR title that the change is "Noetic support for Gentoo" (Noetic is already supported by OE).

**Review by robwoolley — APPROVED** [review]
I tested these changes along with the 2 other ebuild PRs.   It successfully generated the recipes but had difficulty with the docker stage.  The error message was "bash: argument list too long".   It may be necessary to reduce the split_limit.   I am approving these changes so that we can establish a new baseline for ebuild and fix any remaining problems.

**Pull request merged**
