### PR TITLE
Remove tar file after use.

### PR DESCRIPTION
**Pull request by allenh1**
This was much easier than I thought it was going to be.

Connects to #80

### CODE REVIEW

**Comment by allenh1** [comment]
@tfoote I suppose I could have put this in the other PR now that I see the diff. Was expecting something to go wrong, but this seems to work.

**Comment by allenh1** [comment]
Ok, that should be good now. Ready for review.

**Comment by tfoote** [comment]
A way to preserve the archive for repeated runs would be important to have to save time, instead of requiring a full redownload for every run.

**Comment by allenh1** [comment]
@tfoote Maybe a `--save-tars DIR` flag would be appropriate?

**Comment by tfoote** [comment]
I'd suggest something like `--tar-archive-dir` where that directory specifies where to build the archive and it also won't be cleaned up. You can reuse the TempfileManager for this, it's the same logic.

**Comment by allenh1** [comment]
@tfoote Ok, I think this is ready now.

**Pull request merged**
