### PR TITLE
bitbake: Drop year from Copyright lines in generated files

### PR DESCRIPTION
**Pull request by shr-project**
Signed-off-by: Martin Jansa <martin.jansa@lge.com>

### CODE REVIEW

**Comment by allenh1** [comment]
@shr-project is the copyright not required for Open Embedded? I honestly have no idea. @herb-kuta-lge ?

**Comment by herb-kuta-lge** [comment]
@allenh1 < The Travis build seems to have failed because `sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654` failed. Is there a way to retrigger the build?

**Comment by allenh1** [comment]
> The Travis build seems to have failed ... Is there a way to retrigger the build?

Yep! Done.

**Comment by allenh1** [comment]
@herb-kuta-lge feel free to merge this when you're ready

**Pull request merged**
