### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by allenh1**
@tfoote This is the branch I'll use to fix the CI.

Seems that disabling the pull test does the trick. But the reason I have to is still beyond me.

### CODE REVIEW

**Comment by tfoote** [comment]
I'd suggest keeping trying going forward onto xenial. Note that python 3.4 is very old for xenial.

If it works locally, I'd suggest finding a way to disable the pull test only on travis, maybe a command line argument etc.

**Comment by tfoote** [comment]
These issues seem to be in the travis setup before the job even starts. I'd suggest looking through some of the travis tutorials and seeing if there are some basic settings to bring across for docker based testing.

**Comment by allenh1** [comment]
@tfoote I used the `--exclude` flag to skip past the test for `test_pull`. I'm pretty sure it should work now.

**Comment by allenh1** [comment]
Ok, so, some random failures later, and things are ok.

**Pull request merged**
