### PR TITLE
Create GitHub Actions CI workflow based on travis job.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Also removes defunct travis.yml config.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@allenh1 this PR adds GitHub Actions based CI for Superflore and may be useful in testing the 0.3.3 release.

**Review by allenh1 — APPROVED** [review]
@nuclearsandwich thank you much! Looks good to me!

**Comment by allenh1** [comment]
@tfoote can you please remove the travis-ci requirement?

**Comment by nuclearsandwich** [comment]
> @tfoote can you please remove the travis-ci requirement?

I can do that.

**Comment by nuclearsandwich** [comment]
> > can you please remove the travis-ci requirement?
> 
> I can do that.

Done. @allenh1 do you want to make any of the GitHub Actions checks required for merge?

**Comment by allenh1** [comment]
> Done. @allenh1 do you want to make any of the GitHub Actions checks required for merge?

Yes please!

**Comment by nuclearsandwich** [comment]
> Yes please!

I didn't make each individual check required but I did make several os/python-version combinations required and we can update those as platforms evolve.

**Pull request merged**
