### PR TITLE
Upgrade CI

### PR DESCRIPTION
**Pull request by allenh1**
Upgrade ubuntu to bionic, and upgrade python versions to 3.7 and 3.8

Signed-off-by: Hunter L. Allen <hunterlallen@protonmail.com>

---

Connects to #239

### CODE REVIEW

**Comment by allenh1** [comment]
@tfoote do you know what's wrong with `rosdep` and python 3.8? It seems to be unable to detect the os?

**Comment by tfoote** [comment]
I suspect something changed in the rospkg os_detect module that isn't compatible anymore.

**Comment by allenh1** [comment]
> I suspect something changed in the rospkg os_detect module that isn't compatible anymore.

Odd. I'll keep it on 3.6 and 3.7 then, I think.

**Comment by allenh1** [comment]
@tfoote I had to remove `pypy3`, unfortunately. Do you think it's too soon to jump to bionic? I feel like it definitely shouldn't be, but I could go to an earlier release if desired (maybe xenial).

**Pull request merged**
